import Head from "next/head";
import { Inter } from "next/font/google";
import AgeTags from "../components/AgeTags";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app, please don't forget to fill in this template"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Hero /> */}
        {/* <Sections /> */}

        {/* Add age tags — place this where you want the clickable filters to appear */}
        <section className="container mx-auto py-8">
          <h3 className="text-lg font-semibold mb-3">Quick filters — Age</h3>
          <AgeTags />
        </section>
      </main>
    </div>
  );
}